sudo: true
dist: trusty
language:
  - generic
cache:
  - apt

env:
  global:
    - ROS_DISTRO=indigo
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)

# Install package dependencies
before_install:
  # Install ROS
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  # Install doc dependencies
  - sudo apt-get install python-sphinx ros-$ROS_DISTRO-rosdoc-lite
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Prepare rosdep to install dependencies.
  - sudo rosdep init
  - rosdep update

# Create a catkin workspace with the package under integration.
install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin_make
  - source ~/catkin_ws/devel/setup.bash
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .

# Install all dependencies
before_script:
  - cd ~/catkin_ws
  - rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO

# Compile
script:
  # Build the package
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  # Run the tests
  - catkin_make run_tests
  - catkin_test_results
  # Build the docs
  - roscd baldor
  - rosdoc_lite .
